net users /add lol
net users /add lol1
net users /add lol2
net users /add lol3
net users /add lol4
net users /add lol5
net users /add lol6
net users /add lol7
net users /add lol8
net users /add lol9
net users /add lol10